providers = ["php"]

[build]
workdir = "siiupa"

[build.phases.setup]
nixPkgs = [
    "php81", 
    "php81Extensions.pdo", 
    "php81Extensions.mbstring", 
    "php81Extensions.json", 
    "php81Extensions.openssl", 
    "php81Extensions.gd", 
    "php81Extensions.xml", 
    "php81Extensions.dom", 
    "php81Extensions.zip", 
    "php81Extensions.exif", 
    "php81Extensions.pcntl", 
    "php81Extensions.bcmath",
    "composer"
]

[build.phases.build]
cmds = [
    "composer install --no-dev --no-scripts --prefer-dist --optimize-autoloader --no-interaction"
]

[start]
cmd = "php -S 0.0.0.0:$PORT"
workdir = "siiupa"

[environment]
PORT = "3000"