[phps]
version = "8.1"
extensions = ["bcmath", "ctype", "curl", "dom", "fileinfo", "gd", "mbstring", "openssl", "pdo", "pdo_mysql", "pdo_sqlite", "session", "simplexml", "tokenizer", "xml", "xmlreader", "xmlwriter", "zip"]
